import type { AppSettings, CompanyDetails, CustomerDetails, QuoteTemplate } from '@shared/types';
import { DEFAULT_SETTINGS } from '@shared/types';
import { uid } from './id';

export function defaultCompany(): CompanyDetails {
  return {
    name: 'JEEVAN PRAKASH ELECTRICALS & ENTERPRISES',
    titlePrefix: 'M/S.',
    businessDesc: 'GOVT. ELECTRICAL CONTRACTOR',
    contactPerson: 'SACHIN',
    address: 'AMBAD, NASHIK - 10',
    gstin: '',
    pan: '',
    email: 'jpelectricals53@gmail.com',
    phone: '9405307668',
    website: '',
    state: 'Maharashtra',
    stateCode: '27',
    logo: null,
    stamp: null,
    bank: {
      name: '',
      branch: '',
      accountName: '',
      accountNumber: '',
      ifsc: '',
      upi: 'jpelectricals@upi',
      qr: null,
    },
    signatory: { name: 'Sachin', role: 'Authorized Signatory', image: null },
  };
}

export function defaultSettings(): AppSettings {
  const year = String(new Date().getFullYear());
  return { ...DEFAULT_SETTINGS, quoteYear: year, invoicePrefix: 'INV' };
}

export function defaultCustomer(): CustomerDetails {
  return {
    id: uid('cust'),
    name: '',
    company: '',
    attention: '',
    gstin: '',
    pan: '',
    address: '',
    city: '',
    state: '',
    pincode: '',
    phone: '',
    email: '',
    createdAt: new Date().toISOString(),
  };
}

export function defaultTemplates(): QuoteTemplate[] {
  return [
    {
      id: 'default',
      name: 'Classic Industrial',
      isDefault: true,
      isSystem: true,
      accent: '#0f172a',
      font: 'sans',
      headerAlign: 'left',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 90,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.06,
      pageMargin: 28,
      bodyFontSize: 13,
      tableHeaderBg: '#f1f5f9',
      tableStyle: 'bordered',
    },
    {
      id: 'minimal',
      name: 'Minimal',
      isDefault: false,
      isSystem: true,
      accent: '#0f172a',
      font: 'sans',
      headerAlign: 'left',
      showHeaderBorder: false,
      showFooterLine: false,
      logoSize: 80,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.05,
      pageMargin: 32,
      bodyFontSize: 13,
      tableHeaderBg: '#f1f5f9',
      tableStyle: 'minimal',
    },
    {
      id: 'classic',
      name: 'Classic Serif',
      isDefault: false,
      isSystem: true,
      accent: '#7c3aed',
      font: 'serif',
      headerAlign: 'center',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 90,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.05,
      pageMargin: 28,
      bodyFontSize: 13,
      tableHeaderBg: '#f3e8ff',
      tableStyle: 'bordered',
    },
    {
      id: 'modern',
      name: 'Modern Dark',
      isDefault: false,
      isSystem: true,
      accent: '#059669',
      font: 'sans',
      headerAlign: 'left',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 90,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.07,
      pageMargin: 28,
      bodyFontSize: 13,
      tableHeaderBg: '#d1fae5',
      tableStyle: 'zebra',
    },
    {
      id: 'corporate',
      name: 'Corporate Blue',
      isDefault: false,
      isSystem: true,
      accent: '#2563eb',
      font: 'sans',
      headerAlign: 'left',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 80,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.04,
      pageMargin: 30,
      bodyFontSize: 13,
      tableHeaderBg: '#eff6ff',
      tableStyle: 'bordered',
    },
    {
      id: 'executive',
      name: 'Executive',
      isDefault: false,
      isSystem: true,
      accent: '#0f172a',
      font: 'serif',
      headerAlign: 'left',
      showHeaderBorder: false,
      showFooterLine: true,
      logoSize: 90,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.04,
      pageMargin: 34,
      bodyFontSize: 13,
      tableHeaderBg: '#f8fafc',
      tableStyle: 'minimal',
    },
    {
      id: 'gold',
      name: 'Elegant Gold',
      isDefault: false,
      isSystem: true,
      accent: '#b45309',
      font: 'serif',
      headerAlign: 'center',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 90,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.05,
      pageMargin: 28,
      bodyFontSize: 13,
      tableHeaderBg: '#fef3c7',
      tableStyle: 'bordered',
    },
    {
      id: 'contractor',
      name: 'Bold Green',
      isDefault: false,
      isSystem: true,
      accent: '#16a34a',
      font: 'sans',
      headerAlign: 'left',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 90,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.06,
      pageMargin: 28,
      bodyFontSize: 13,
      tableHeaderBg: '#dcfce7',
      tableStyle: 'zebra',
    },
    {
      id: 'royal',
      name: 'Financier Royal',
      isDefault: false,
      isSystem: true,
      accent: '#6d28d9',
      font: 'serif',
      headerAlign: 'center',
      showHeaderBorder: true,
      showFooterLine: true,
      logoSize: 80,
      signatureSize: 120,
      stampSize: 110,
      watermarkOpacity: 0.04,
      pageMargin: 30,
      bodyFontSize: 13,
      tableHeaderBg: '#f5f3ff',
      tableStyle: 'minimal',
    },
  ];
}
